version: '3'

services:
  mongo:
    image: mongo:3.4-jessie
  redis:
    image: redis:5-alpine
  cassandra:
    image: cassandra
  app:
    build: ./
    depends_on:
      - mongo
      - redis
      - cassandra
    ports:
      - '3000:3000'
