version: '3'

services:
  mongo:
    image: mongo:3.4-jessie
  redis:
    image: redis:5-alpine
  cassandra:
    image: cassandra
  nats:
    image: nats
  elasticsearch:
    image: elasticsearch:5.6-alpine
  app:
    build: ./
    depends_on:
      - mongo
      - redis
      - cassandra
      - nats
      - elasticsearch
    ports:
      - '3000:3000'
